##Slicing and Shape

In [2]:
import torch

In [3]:
my_torch=torch.arange(14)
my_torch

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [4]:
#Reshape and view
my_t=my_torch.reshape(7,2)
my_t

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13]])

In [5]:
my_t1=my_torch.reshape(2,-1)
my_t1

tensor([[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13]])

In [6]:
my_t1=my_torch.reshape(-1,2)
my_t1

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13]])

In [23]:
my_t5=torch.arange(15)
my_t5_reshaped=my_t5.reshape(-1,3)
my_t5_reshaped

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [14]:
my_t5[4]=99
my_t5

tensor([ 0,  1,  2,  3, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
my_t5[4:8]

tensor([99,  5,  6,  7])

In [18]:
my_t5[4:8:2]

tensor([99,  6])

In [27]:
my_t5=torch.arange(15)
my_t5_reshaped=my_t5.reshape(-1,3)
print(my_t5_reshaped[:,1])
print(my_t5_reshaped[:,1:])
print(my_t5_reshaped[:,2:])

tensor([ 1,  4,  7, 10, 13])
tensor([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11],
        [13, 14]])
tensor([[ 2],
        [ 5],
        [ 8],
        [11],
        [14]])


## Math Operations

In [3]:
import torch

# Define example tensors
a = torch.tensor([10, 25, 30, 42])
b = torch.tensor([2, 4, 6, 8])

print("Tensor a:", a)
print("Tensor b:", b)
print("")

# 🧮 Addition
print("Addition: a + b =", a + b)

# ➖ Subtraction
print("Subtraction: a - b =", a - b)

# ✖️ Element-wise Multiplication
print("Multiplication: a * b =", a * b)

# ➗ Integer Division
print("Division: a // b =", a // b)

# ➗ Division
print("Division: a / b =", a / b)

# 🔁 Remainder (Modulus)
print("Remainder (a % b):", a % b)

# ⬆️ Exponentiation (Power)
print("Exponentiation (a ** 2):", a ** 2)

# Optional: Advanced - Square root
print("Square root of a:", torch.sqrt(a.float()))


Tensor a: tensor([10, 25, 30, 42])
Tensor b: tensor([2, 4, 6, 8])

Addition: a + b = tensor([12, 29, 36, 50])
Subtraction: a - b = tensor([ 8, 21, 24, 34])
Multiplication: a * b = tensor([ 20, 100, 180, 336])
Division: a // b = tensor([5, 6, 5, 5])
Division: a / b = tensor([5.0000, 6.2500, 5.0000, 5.2500])
Remainder (a % b): tensor([0, 1, 0, 2])
Exponentiation (a ** 2): tensor([ 100,  625,  900, 1764])
Square root of a: tensor([3.1623, 5.0000, 5.4772, 6.4807])
